
DROP TYPE ACMA_DUTY_RESULT_TBL
-- TYPE
CREATE OR REPLACE TYPE ACMA_DUTY_RESULT_OBJ AS OBJECT(
       DUTY_ID NUMBER,
       DOCTOR_ID NUMBER,
       CONSULTING_DATE DATE,
       CONSULTING_TIME_PART_BEGIN NUMBER,
       CONSULTING_TIME_PART_END NUMBER
)

CREATE OR REPLACE TYPE ACMA_DUTY_RESULT_TBL AS TABLE OF ACMA_DUTY_RESULT_OBJ
--


-- Get duties
CREATE OR REPLACE FUNCTION ACMA_DUTY_VIEW(
       DOCTOR_ID_ IN NUMBER
)
RETURN ACMA_DUTY_RESULT_TBL
AS 
  RES_TBL ACMA_DUTY_RESULT_TBL;
  BEGIN_TIME DATE;
  BEGIN_TIME_VAR VARCHAR2(24);
  END_TIME DATE;
  END_TIME_VAR VARCHAR(24);
  TIME_GAP NUMBER;
BEGIN
  FOR LINE IN (SELECT D.DUTY_ID,D.CONSULTING_DATE,D.CONSULTING_TIME_BEGIN,D.CONSULTING_TIME_END,D.TICKETS_PER_DAY,D.REMAINING_TICKET
    FROM ACMA_DUTY D
    WHERE D.DOCTOR_ID = DOCTOR_ID_ AND D.LOCK_STATUS =0)
  LOOP
    BEGIN_TIME_VAR := TRUNC(LINE.CONSULTING_DATE,'YEAR') || ':' || LINE.CONSULTING_TIME_BEGIN;
    END_TIME_VAR := TO_CHAR(LINE.CONSULTING_DATE,'YYYY/MM/DD')|| ':' || LINE.CONSULTING_TIME_END;

    --BEGIN_TIME := TO_DATE(BEGIN_TIME_VAR,'yyyy/mm/dd:hh24:mi:ss');
    BEGIN_TIME := TO_DATE(line.consulting_time_begin,'hh24:mi:ss');
    --END_TIME := TO_DATE(END_TIME_VAR,'YYYY/MM/DD:HH24:MI:SS');
    END_TIME := TO_DATE(line.consulting_time_end,'hh24:mi:ss');
    
    TIME_GAP := (END_TIME - BEGIN_TIME) * 1440 ;

    DBMS_OUTPUT.put_line('This line  '|| LINE.DUTY_ID || ' with : ' || to_char(trunc(sysdate) + (END_TIME - BEGIN_TIME),'HH24 "Hours" MI "Minutes"') || ' total minute ' || time_gap);
  END LOOP;
  
  RETURN RES_TBL;
END;

------------------------------------ SQL
SELECT D.DUTY_ID,D.CONSULTING_DATE,D.CONSULTING_TIME_BEGIN,D.CONSULTING_TIME_END,D.TICKETS_PER_DAY,D.REMAINING_TICKET
FROM ACMA_DUTY D
WHERE D.DOCTOR_ID = 3 AND D.LOCK_STATUS =0


-------------------------------
DECLARE 
    RES_LIST ACMA_DUTY_RESULT_TBL;
BEGIN
  RES_LIST := ACMA_DUTY_VIEW(5);
  --FOR X IN 1..RES_LIST.COUNT 
  --  LOOP
  --    DBMS_OUTPUT.PUT_LINE('DATA :' || RES_LIST(X).DOCTOR_ID || '  ' || RES_LIST(X).FULLNAME || '  ' || RES_LIST(X).AVAILABLE_ON_WEEKEND || '  ' || RES_LIST(X).ROOM_NUMBER || '  ' || RES_LIST(X).DESCRIPTION );
  --END LOOP;
END;
