
DROP TYPE ACMA_DUTY_RESULT_TBL
-- TYPE
CREATE OR REPLACE TYPE ACMA_DUTY_RESULT_OBJ AS OBJECT(
       DUTY_ID NUMBER,
       DOCTOR_ID NUMBER,
       CONSULTING_DATE NUMBER,
       CONSULTING_TIME_BEGIN VARCHAR2(15),
       CONSULTING_TIME_END VARCHAR2(15),
       REMAINING_TICKET NUMBER
)

CREATE OR REPLACE TYPE ACMA_DUTY_RESULT_TBL AS TABLE OF ACMA_DUTY_RESULT_OBJ
--


-- Get duties
CREATE OR REPLACE FUNCTION ACMA_DUTY_VIEW(
       DOCTOR_ID_ IN NUMBER
)
RETURN ACMA_DUTY_RESULT_TBL
AS 
  RES_TBL ACMA_DUTY_RESULT_TBL;
  
BEGIN
  SELECT ACMA_DUTY_RESULT_OBJ( D.DUTY_ID, D.DOCTOR_ID, D.CONSULTING_DATE, D.CONSULTING_TIME_BEGIN, D.CONSULTING_TIME_END, D.REMAINING_TICKET )
  BULK COLLECT INTO RES_TBL
  FROM ACMA_DUTY D
  WHERE D.DOCTOR_ID = DOCTOR_ID_ AND D.LOCK_STATUS =0;
  
  RETURN RES_TBL;
END;

------------------------------------ SQL
SELECT D.DUTY_ID,D.CONSULTING_DATE,D.CONSULTING_TIME_BEGIN,D.CONSULTING_TIME_END,D.TICKETS_PER_DAY,D.REMAINING_TICKET
FROM ACMA_DUTY D
WHERE D.DOCTOR_ID = 7 AND D.LOCK_STATUS =0


------------------------------- TEST 
DECLARE 
    RES_LIST ACMA_DUTY_RESULT_TBL;
BEGIN
  RES_LIST := ACMA_DUTY_VIEW(7);
  FOR X IN 1..RES_LIST.COUNT 
    LOOP
      DBMS_OUTPUT.PUT_LINE('DATA :' || RES_LIST(X).DOCTOR_ID || '  ' || RES_LIST(X).CONSULTING_DATE || '  ' || RES_LIST(X).CONSULTING_TIME_BEGIN || '  ' || RES_LIST(X).CONSULTING_TIME_END || '  ' || RES_LIST(X).REMAINING_TICKET );
  END LOOP;
END;
