
-- TYPE
CREATE OR REPLACE TYPE ACMA_DOCTOR_S_RESULT_OBJ AS OBJECT(
       DOCTOR_ID NUMBER,
       FULLNAME VARCHAR2(255),
       AVAILABLE_ON_WEEKEND NUMBER,
       ROOM_NUMBER NUMBER,
       DESCRIPTION VARCHAR(512)
)

CREATE OR REPLACE TYPE ACMA_DOCTOR_S_RESULT_TBL AS TABLE OF ACMA_DOCTOR_S_RESULT_OBJ
--

CREATE OR REPLACE FUNCTION ACMA_DOCTOR_SEARCH_BY_NAME(
       NAME_ IN VARCHAR2
)
RETURN ACMA_DOCTOR_S_RESULT_TBL
AS RES_TBL ACMA_DOCTOR_S_RESULT_TBL;
BEGIN
  SELECT ACMA_DOCTOR_S_RESULT_OBJ(D.DOCTOR_ID,D.FULLNAME,D.AVAILABLE_ON_WEEKEND,D.ROOM_NUMBER,S.DESCRIPTION)
  BULK COLLECT INTO RES_TBL
  FROM ACMA_DOCTOR D
  LEFT JOIN ACMA_DOCTOR_SPECIALTY DS ON D.DOCTOR_ID = DS.DOCTOR_ID
  LEFT JOIN ACMA_SPECIALTY S ON DS.SPECIALTY_ID = S.SPECIALTY_ID
  WHERE lower(FULLNAME) LIKE lower('%'||NAME_||'%')
  ORDER BY D.FULLNAME;
  
  RETURN RES_TBL;
END;

------------------------------------ SQL
SELECT D.DOCTOR_ID,D.FULLNAME,D.AVAILABLE_ON_WEEKEND,D.ROOM_NUMBER,S.DESCRIPTION FROM ACMA_DOCTOR D LEFT JOIN ACMA_DOCTOR_SPECIALTY DS ON D.DOCTOR_ID = DS.DOCTOR_ID LEFT JOIN ACMA_SPECIALTY S ON DS.SPECIALTY_ID = S.SPECIALTY_ID WHERE lower(FULLNAME) LIKE lower('%nu%') ORDER BY D.FULLNAME 

-------------------------------
DECLARE 
    RES_LIST ACMA_DOCTOR_S_RESULT_TBL;
BEGIN
  RES_LIST := ACMA_DOCTOR_SEARCH_BY_NAME('nu');
  FOR X IN 1..RES_LIST.COUNT 
    LOOP
      DBMS_OUTPUT.PUT_LINE('DATA :' || RES_LIST(X).DOCTOR_ID || '  ' || RES_LIST(X).FULLNAME || '  ' || RES_LIST(X).AVAILABLE_ON_WEEKEND || '  ' || RES_LIST(X).ROOM_NUMBER || '  ' || RES_LIST(X).DESCRIPTION );
  END LOOP;
END;

7,6,9

delete from acma_doctor where doctor_id = 9






select * from acma_doctor
select * from acma_appoinment
select * from acma_specialty
select * from ACMA_DOCTOR_SPECIALTY

