CREATE OR REPLACE TYPE ACMA_PATIENT_OBJ AS OBJECT(
       PATIENT_ID NUMBER,
       FULLNAME VARCHAR2(255),
       NIC VARCHAR2(32),
       TELEPHONE NUMBER,
       ADDRESS VARCHAR2 (256)
)

CREATE OR REPLACE TYPE ACMA_PATIENT_TBL AS TABLE OF ACMA_PATIENT_OBJ

-----------------------FUNCTION

CREATE OR REPLACE FUNCTION ACMA_SINGLE_PATIENT(NIC_NO VARCHAR2)
RETURN ACMA_PATIENT_TBL
AS RESULT_TABLE ACMA_PATIENT_TBL;
BEGIN
  SELECT ACMA_PATIENT_OBJ(PATIENT_ID, FULLNAME, NIC, TELEPHONE, ADDRESS)
  BULK COLLECT INTO RESULT_TABLE
  FROM ACMA_PATIENT
  WHERE NIC = NIC_NO
  ORDER BY PATIENT_ID;
  RETURN RESULT_TABLE;
END;


SELECT PATIENT_ID, FULLNAME, NIC, TELEPHONE, ADDRESS
  FROM ACMA_PATIENT
  WHERE NIC = '44444444V'

