-------------------------------------------- Sequence 
CREATE SEQUENCE ACMA_DUTY_ID
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 20;

-------------------------------------------- Procedure

CREATE OR REPLACE PROCEDURE ACMA_DUTY_ADD(
       DOCTOR_ID_ IN NUMBER,
       CONSULTING_DATE_ IN DATE,
       CONSULTING_TIME_BEGIN_ IN VARCHAR2,
       CONSULTING_TIME_END_ IN VARCHAR2,
       LOCK_STATUS_ IN NUMBER,
       TICKETS_PER_DAY_ IN NUMBER,
       REMAINING_TICKET_ IN NUMBER
)
IS
BEGIN
  INSERT INTO ACMA_DUTY
  VALUES(
       ACMA_DUTY_ID.NEXTVAL,
       DOCTOR_ID_,
       CONSULTING_DATE_,
       CONSULTING_TIME_BEGIN_,
       CONSULTING_TIME_END_,
       LOCK_STATUS_,
       TICKETS_PER_DAY_,
       REMAINING_TICKET_
  );
  COMMIT;
END;

DECLARE
BEGIN
  ACMA_DUTY_ADD(03,SYSDATE,'13:00:00','15:00:00',0,6,4);
END;
  
