CREATE TABLE ACMA_APPOINMENT(
       APPOINMENT_ID NUMBER NOT NULL PRIMARY KEY,
       PATIENT_ID NUMBER REFERENCES ACMA_PATIENT(PATIENT_ID),
       DOCTOR_ID NUMBER REFERENCES ACMA_DOCTOR(DOCTOR_ID),
       CREATED_DATE_TIME TIMESTAMP DEFAULT SYSDATE,
       APPOINTMENT_DATE_TIME TIMESTAMP NOT NULL,
       CONSULTING_CATOGERY varchar2(128),
       STATUS NUMBER(1,0)
)
