CREATE TABLE ACMA_RECEPTION(
       RECEPTIONIST_ID NUMBER NOT NULL PRIMARY KEY,
       RECEPTIONIST_NAME VARCHAR(128),
       RECEPTIONIST_EMAIL VARCHAR(128),
       TELEPHONE NUMBER,
       USERNAME VARCHAR(255) NOT NULL,
       PASSWORD VARCHAR(255)
)
