
INSERT INTO ACMA_DOCTOR_SPECIALTY
VALUES (1,1,1);
INSERT INTO ACMA_DOCTOR_SPECIALTY
VALUES (2,1,2);
INSERT INTO ACMA_DOCTOR_SPECIALTY
VALUES (3,2,3);
INSERT INTO ACMA_DOCTOR_SPECIALTY
VALUES (4,3,4);
INSERT INTO ACMA_DOCTOR_SPECIALTY
VALUES (5,4,5);

COMMIT 
